/// Kata percakapan sehari-hari diubah ke bentuk baku sebelum aturan dan pencarian dijalankan, supaya pertanyaan santai
/// ("gimana bikin nasgor yg enak", "mie instan aman ga sih") dipahami sama seperti pertanyaan formal. Teks yang
/// ditampilkan kepada pengguna tidak diubah.
library;

const _words = {
  'gimana': 'bagaimana',
  'gmn': 'bagaimana',
  'gmna': 'bagaimana',
  'gak': 'tidak',
  'ga': 'tidak',
  'gk': 'tidak',
  'nggak': 'tidak',
  'ngga': 'tidak',
  'enggak': 'tidak',
  'engga': 'tidak',
  'kagak': 'tidak',
  'tak': 'tidak',
  'aja': 'saja',
  'ajah': 'saja',
  'doang': 'saja',
  'udah': 'sudah',
  'udh': 'sudah',
  'dah': 'sudah',
  'blm': 'belum',
  'bikin': 'membuat',
  'bkin': 'membuat',
  'pake': 'pakai',
  'emang': 'memang',
  'kalo': 'kalau',
  'klo': 'kalau',
  'kl': 'kalau',
  'gitu': 'begitu',
  'gini': 'begini',
  'banget': 'sekali',
  'bgt': 'sekali',
  'kayak': 'seperti',
  'kyk': 'seperti',
  'yg': 'yang',
  'dgn': 'dengan',
  'utk': 'untuk',
  'untk': 'untuk',
  'krn': 'karena',
  'soalnya': 'karena',
  'jd': 'jadi',
  'bs': 'bisa',
  'pengen': 'ingin',
  'pingin': 'ingin',
  'pgn': 'ingin',
  'mo': 'mau',
  'apaan': 'apa',
  'napa': 'kenapa',
  'knp': 'kenapa',
  'td': 'tadi',
  'tdi': 'tadi',
  'skrg': 'sekarang',
  'skrng': 'sekarang',
  'sy': 'saya',
  'gw': 'saya',
  'gue': 'saya',
  'gua': 'saya',
  'lu': 'anda',
  'nasgor': 'nasi goreng',
  'migor': 'mi goreng',
  'indomi': 'mi instan',
  'indomie': 'mi instan',
  'makasih': 'terima kasih',
  'mksh': 'terima kasih',
  'thx': 'terima kasih',
  'tq': 'terima kasih',
  'masakin': 'masak',
  'ngerebus': 'merebus',
  'ngegoreng': 'menggoreng',
  'nyimpen': 'menyimpan',
  'nyimpan': 'menyimpan',
  'ngukus': 'mengukus',
  'ditaro': 'ditaruh',
  'brp': 'berapa',
  'bnyk': 'banyak',
  'dikit': 'sedikit',
  'kriuk': 'renyah',
  'garing': 'renyah',
  'crispy': 'renyah',
  'krispi': 'renyah',
  'sdikit': 'sedikit',
};

/// Bentuk baku dari [text]: huruf kecil, kata santai diganti, dan huruf yang diulang ("enakkk") dirapikan.
String formalize(String text) {
  final lower = text.toLowerCase().replaceAllMapped(RegExp(r'([a-z])\1{2,}'), (m) => m[1]!);
  return lower.replaceAllMapped(RegExp(r'[a-z]+'), (m) => _words[m[0]] ?? m[0]!);
}
